[build]
	base = "/"
	publish = "build/pshry.com/"
	command = "npm run build"

# ---------------
# Redirects
# ---------------

[[redirects]]
	from = "/github"
	to = "https://github.com/paulshryock/paul-shryock"
	status = 200
	force = true
	headers = {X-From = "Netlify"}

[[redirects]]
	from = "/legacy/*"
	to = "https://pshry.com/:splat"
	status = 307
