[build]
	base = "/"
	publish = "build/pshry.com/"
	command = "npm run build"

#####################
#     Redirects     #
#####################

[[redirects]]
	from = "/*"
	to = "/404?search=:splat"
	status = 404

[[redirects]]
	from = "/github"
	to = "https://github.com/paulshryock"
	status = 200
	force = true
	headers = {X-From = "Netlify"}
