[build]
	base = "/"
	publish = "build/pshry.com/"
	command = "npm run build"

#####################
#     Redirects     #
#####################

[[redirects]]
	from = "http://pshry-com.netlify.app"
	to = "https://www.paulshryock.dev/"
	status = 301
	force = true

[[redirects]]
	from = "http://pshry-com.netlify.app/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://pshry-com.netlify.app"
	to = "https://www.paulshryock.dev/"
	status = 301
	force = true

[[redirects]]
	from = "https://pshry-com.netlify.app/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 301
	force = true

[[redirects]]
	from = "http://pshry.com"
	to = "https://www.paulshryock.dev/"
	status = 302
	force = true

[[redirects]]
	from = "http://pshry.com/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 302
	force = true

[[redirects]]
	from = "https://pshry.com"
	to = "https://www.paulshryock.dev/"
	status = 302
	force = true

[[redirects]]
	from = "https://pshry.com/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 302
	force = true
