[build]
	base = "/"
	publish = "build/pshry.com/"
	command = "npm run build"

#####################
#     Redirects     #
#####################

[[redirects]]
	from = "/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 302

[[redirects]]
	from = "/behance"
	to = "https://www.behance.net/pshry"
	status = 200
	force = true
	headers = {X-From = "Netlify"}

[[redirects]]
	from = "/dribbble"
	to = "https://dribbble.com/pshry"
	status = 200
	force = true
	headers = {X-From = "Netlify"}

[[redirects]]
	from = "/github"
	to = "https://github.com/paulshryock"
	status = 200
	force = true
	headers = {X-From = "Netlify"}

[[redirects]]
	from = "/linkedin"
	to = "https://www.linkedin.com/in/paulshryock"
	status = 200
	force = true
	headers = {X-From = "Netlify"}

[[redirects]]
	from = "/twitter"
	to = "https://twitter.com/paul_shryock"
	status = 200
	force = true
	headers = {X-From = "Netlify"}
