name: CI

on: push

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5'
          cache: 'npm'
      - name: JS linting
        run: |
          npm ci
          npm run format
          npm run lint:js

  Typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5'
          cache: 'npm'
      - name: JS type checking
        run: |
          npm ci
          npm run typecheck

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5'
          cache: 'npm'
      - name: JS unit tests
        run: |
          npm ci
          npm test

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5'
          cache: 'npm'
      - name: Build
        run: |
          npm ci
          npm run buildscript
          npm run healthcheck